### ISSUE TITLE
Can u update this mod? plz

### ISSUE THREAD

**Issue by zldi** [Turtlefight/SatisfactoryBuildableResourceNodes#1]
After the game update on November 24th, the mod not works.
so,can u fix it?
I really want to use it.
plz

**Comment by Turtlefight** [comment]
Hi, sorry RL has kept me busy the last week so i didn't manage to update this mod in time.
Faster Manual Crafting, Water Pools & Fluid AWESOME Sink are already updated.

Buildable Resource Nodes (including the MM Addon) & More Color Slots will be updated within the next few days.

Thanks for using the mod & sorry for the delayed update!

**Comment by Saibotb94** [comment]
Hey, Freue mich schon drauf wenn der mod wieder funktioniert

**Comment by Rai557** [comment]
Hello. I really want to keep playing my saved game and not start a new one.
Please can you update soon.

**Comment by Turtlefight** [comment]
Updated for U5 with v1.1.4, should be available on ficsit.app within a few minutes
