### ISSUE TITLE
Please add Refined Powers Support

### ISSUE THREAD

**Issue by hecker187** [Turtlefight/SatisfactoryBuildableResourceNodes#2]
Can you please add Ores from the Refined Powers Mod? I don't care if it's in the normal mod or in the addon

Here´s a link to the refined Powers Mod: [https://ficsit.app/mod/DGiLzB3ZErWu2V](url)

**Comment by Turtlefight** [comment]
Hi, sorry there are currently no plans to support any other mods except More Milestones.

It's currently too much work to add new ores with how the mod currently works.
I'll try to refactor it sometime in the future to hopefully support any modded ores as well - but no ETA on this for now unfortunately.

**Comment by Turtlefight** [comment]
Discontinued - please use https://ficsit.app/mod/BuildableResourceNodesRedux
