### ISSUE TITLE
Mod Broken after Update v0.6.1.2 on Early Access

### ISSUE THREAD

**Issue by ghost** [Turtlefight/SatisfactoryBuildableResourceNodes#4]
The radii of the node patches are way too large. v0.6.1.3 fixed this issue for all vanilla interactables but the mod's interactables (the nodes) still have this issue.

**Comment by soxism** [comment]
Can confirm when placing new Node the Hitboxes are massive.

**Comment by budak7273** [comment]
Use this mod instead: https://ficsit.app/mod/BuildableResourceNodesRedux

**Comment by Turtlefight** [comment]
Discontinued - use https://ficsit.app/mod/BuildableResourceNodesRedux
